version: '3.1'
services:
  app:
    container_name: springboot-postgresql
    image: springboot-app
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - postgresqldb
  postgresqldb:
    image: postgres
    build:
      context: ./
      dockerfile: Dockerfile.postgres
    ports:
      - "5432:5432"
    environment:
      - PGDATA=/var/lib/postgresql/data
      - POSTGRES_PASSWORD=123456
      - POSTGRES_USER=user