version: '3.9'
services:

  nginx:
    image: nginx:1.25.2-alpine
    container_name: nginx
    volumes:
      - /var/log/nginx:/var/log/nginx
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
    ports:
      - "50:50"
    hostname: nginx
    networks:
      - network1
    depends_on:
      - user-app
      - user-db
    restart: unless-stopped

  user-app:
    container_name: user-app
    image: manosov/user-minibank
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    depends_on:
      - user-db
    networks:
      - network1
    restart: unless-stopped

  user-db:
    container_name: user-db
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      - PGDATA=/var/lib/postgresql/data
      - POSTGRES_PASSWORD=123456
      - POSTGRES_USER=user
    networks:
      - network1
    restart: unless-stopped


networks:
  network1:
    name: network1
    driver: bridge