name: CD
'on':
  push:
    branches:
      - main
      - develop
      - feature/cd
  pull_request:
    branches:
      - main
      - develop
      - feature/cd
  workflow_dispatch:
jobs:
  build:
    name: Build and push Docker image to Dockerhub
    runs-on: ubuntu-20.04
    steps:
      # заливаем исходники
      - name: Check out code
        uses: actions/checkout@v3

      # установка java
      - name: Setup JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: gradle

      # логин в докерхаб
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          context: .
          file: ./backend/services/account/Dockerfile
          push: true
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
    
      # установкаgradle и запуск сборки
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@ccb4328a959376b642e027874838f60f8e596de3
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Execute Gradle build
        run: ./gradlew --no-daemon clean build

        
      # сбор и деплой образа в докерхаб
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: docker-compose
          push: true
          tags: latest
          labels: latest
