name: CD

on:
  push:
#    tags:
#      - "v*.*.*"
    branches:
      - main
    paths:
      - './'
      - 'src'
      - '.github/workflows/CD*'
  workflow_dispatch:
    inputs:
      reason:
        description: "Name the reason"
        default: "Just because"
        required: true
      version:
        description: 'Docker image version'
        required: true
        default: 'latest'
jobs:
  build:
    name: Build and push Docker image to Dockerhub
    runs-on: ubuntu-20.04
#    outputs:
#      version: ${{ env.VERSION }}

    steps:
      # заливаем исходники
      - name: Check out code
        uses: actions/checkout@v3

      # установка java
      - name: Setup JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: gradle

      # логин в докерхаб
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      # сбор и деплой браза в докерхаб
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: latest
          labels: latest

