name: mini-workflow JAVA CI with gradle
on:
  push:
    branches:
      - master
      - main
      - develop
      - CI
  pull_request:
    branches:
      - master
      - main
      - develop
      - CI
  workflow_dispatch: null
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Setup JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: gradle
#      - name: Grant execute permission for gradlew
#        run: chmod +x gradlew
#      - name: Build with Gradle
#        run: ./gradlew build


#      - name: Build with Gradle
#        uses: gradle/gradle-build-action@bd5760595778326ba7f1441bcf7e88b49de61a25 # v2.6.0
#        with:
#          arguments: build
      - name: Validate Gradle wrapper matches official SHA-256 checksums for security
        uses: gradle/wrapper-validation-action@v1
      - name: Build with Gradle
        run: ./gradlew build

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: ktlint
        uses: block42-blockchain-company/ktlint-action@master