name: mini-workflow JAVA CI with gradle
on:
  push:
    branches:
      - master
      - main
      - develop
      - CI
  pull_request:
    branches:
      - master
      - main
      - develop
      - CI
  workflow_dispatch: null
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Setup JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: gradle
#          architecture: x64
        run: ./gradlew build

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@ccb4328a959376b642e027874838f60f8e596de3
#      - name: Run the Gradle package task
#        uses: gradle/gradle-build-action@749f47bda3e44aa060e82d7b3ef7e40d953bd629
#        with:
#          arguments: -b ci.gradle package
#      - name: Run the Gradle package task
#        uses: gradle/gradle-build-action@749f47bda3e44aa060e82d7b3ef7e40d953bd629
#        with:
#          arguments: build

#      - name: Setup Gradle
#        uses: ./gradlew/gradle-build-action@v2
#      - name: install dependencies
#        uses: ./gradlew --console plain dependencies
#      - name: Execute Gradle build
#        run: ./gradlew build


#      - name: Grant execute permission for gradlew
#        run: chmod +x gradlew
#      - name: Build with Gradle
#        run: ./gradlew build


#      - name: Build with Gradle
#        uses: gradle/gradle-build-action@bd5760595778326ba7f1441bcf7e88b49de61a25 # v2.6.0
#        with:
#          arguments: build
#      - name: Validate Gradle wrapper matches official SHA-256 checksums for security
#        uses: gradle/wrapper-validation-action@v1
#      - name: Grant execute permission for gradlew
#        run: chmod +x gradlew
#      - name: Build with Gradle
#        run: ./gradlew build -D, --refresh-dependencies
      #run: ./gradlew bootJar
  #      uses: eskatos/gradle-command-action@v1
   #     with:
    #      gradle-version: current

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: ktlint
        uses: block42-blockchain-company/ktlint-action@master